import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Copy, Check } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

interface NarrativeSummaryProps {
  narrative: string;
  provider: string;
}

export function NarrativeSummary({ narrative, provider }: NarrativeSummaryProps) {
  const [copied, setCopied] = useState(false);
  const [expanded, setExpanded] = useState(false);

  const isLong = narrative.length > 500;
  const displayNarrative = !expanded && isLong
    ? narrative.slice(0, 500) + '...'
    : narrative;

  const handleCopy = async () => {
    await navigator.clipboard.writeText(narrative);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="flex items-center gap-2">
            AI Narrative Summary
            <Badge variant="secondary" className="text-xs">
              Generated by {provider}
            </Badge>
          </CardTitle>
          <Button
            variant="outline"
            size="sm"
            onClick={handleCopy}
            className="gap-2"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4" />
                Copied
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                Copy
              </>
            )}
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        <div className="prose prose-sm dark:prose-invert max-w-none">
          <ReactMarkdown>{displayNarrative}</ReactMarkdown>
        </div>

        {isLong && (
          <Button
            variant="link"
            onClick={() => setExpanded(!expanded)}
            className="mt-4 px-0"
          >
            {expanded ? 'Show less' : 'Read more'}
          </Button>
        )}
      </CardContent>
    </Card>
  );
}
